server:
   port: 2002


#DATABASE AND SPRING DATA JPA CONFIGURATION
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/projecteidiko
    username: root
    password: root
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  application:
    name: PAYMENTT-SERVICE
  config:
     import: optional:configserver:http://localhost:8888

#Eureka Server Configuration
#eureka:
#  instance:
#    hostname: localhost
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#       default-zone: http://localhost:8761/eureka

logging:
  file:
    path: C:\Users\Sreenivas Bandaru\Downloads\Sisu\Log files