server:
   port: 2001


#DATABASE AND SPRING DATA JPA CONFIGURATION
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/projecteidiko
    username: root
    password: root
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  application:
    name: ORDERR-SERVICE
  config:
     import: optional:configserver:http://localhost:8888
#Eureka Server Configuration
#eureka:
#  instance:
#    hostname: localhost
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#       default-zone: http://localhost:8761/eureka


#ELK log file configuration
#logging:
#  file:
#    path: C:\Users\Sreenivas Bandaru\Downloads\Sisu\Log files
    
#Actuator,Circuit brfeaker,resilience4j,Retry and rateLimiter Configuration
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
            
resilience4j:
  circuitbreaker:
    instances:
      bookOrderBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: count-based
      fetchBookOrderBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: count-based
  retry:
    instances:
      fetchBookOrderRetry:
        max-attempts: 3
        wait-duration: 5s     